# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/MultwithTrojan/MultwithTrojan.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MultwithTrojan || ORIG_REF_NAME==MultwithTrojan}]

# IP: bd/MultwithTrojan/ip/MultwithTrojan_processing_system7_0_0/MultwithTrojan_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MultwithTrojan_processing_system7_0_0 || ORIG_REF_NAME==MultwithTrojan_processing_system7_0_0}]

# IP: bd/MultwithTrojan/ip/MultwithTrojan_multwithTrojan_0_0/MultwithTrojan_multwithTrojan_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MultwithTrojan_multwithTrojan_0_0 || ORIG_REF_NAME==MultwithTrojan_multwithTrojan_0_0}]

# IP: bd/MultwithTrojan/ip/MultwithTrojan_processing_system7_0_axi_periph_0/MultwithTrojan_processing_system7_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MultwithTrojan_processing_system7_0_axi_periph_0 || ORIG_REF_NAME==MultwithTrojan_processing_system7_0_axi_periph_0}]

# IP: bd/MultwithTrojan/ip/MultwithTrojan_rst_processing_system7_0_100M_0/MultwithTrojan_rst_processing_system7_0_100M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MultwithTrojan_rst_processing_system7_0_100M_0 || ORIG_REF_NAME==MultwithTrojan_rst_processing_system7_0_100M_0}]

# IP: bd/MultwithTrojan/ip/MultwithTrojan_auto_pc_0/MultwithTrojan_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MultwithTrojan_auto_pc_0 || ORIG_REF_NAME==MultwithTrojan_auto_pc_0}]

# XDC: bd/MultwithTrojan/ip/MultwithTrojan_processing_system7_0_0/MultwithTrojan_processing_system7_0_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==MultwithTrojan_processing_system7_0_0 || ORIG_REF_NAME==MultwithTrojan_processing_system7_0_0}] {/inst }]/inst ]]

# XDC: bd/MultwithTrojan/ip/MultwithTrojan_rst_processing_system7_0_100M_0/MultwithTrojan_rst_processing_system7_0_100M_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MultwithTrojan_rst_processing_system7_0_100M_0 || ORIG_REF_NAME==MultwithTrojan_rst_processing_system7_0_100M_0}]

# XDC: bd/MultwithTrojan/ip/MultwithTrojan_rst_processing_system7_0_100M_0/MultwithTrojan_rst_processing_system7_0_100M_0_ooc.xdc

# XDC: bd/MultwithTrojan/ip/MultwithTrojan_rst_processing_system7_0_100M_0/MultwithTrojan_rst_processing_system7_0_100M_0_board.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MultwithTrojan_rst_processing_system7_0_100M_0 || ORIG_REF_NAME==MultwithTrojan_rst_processing_system7_0_100M_0}]

# XDC: bd/MultwithTrojan/ip/MultwithTrojan_auto_pc_0/MultwithTrojan_auto_pc_0_ooc.xdc

# XDC: bd/MultwithTrojan/MultwithTrojan_ooc.xdc
